services:

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "june-pgdata:/var/lib/postgresql/data"
    restart: always
    networks:
      - default


  site:
    build:
      context: .
      dockerfile: docker/website.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    hostname: "website"
    networks:
      - default
      - nginx_network

  admin:
    build:
      context: .
      dockerfile: docker/admin.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    hostname: "admin"
    networks:
      - default
      - nginx_network

volumes:
  june-pgdata:

networks:
  nginx_network:
    external: true