name: Build and push to ghcr

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - website
          - admin

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/${{ matrix.service }}.Dockerfile

          push: true
          platforms: linux/arm64
          tags: ghcr.io/june-rl/june.pet-${{ matrix.service }}:latest